### ISSUE TITLE
Compilation error using MSYS2

### ISSUE THREAD

**Issue by mdecourse** [KmolYuan/Pyslvs-UI#20]
Traceback (most recent call last):
      File "launch_pyslvs.py", line 12, in <module>
        main()
      File "Y:\tmp\Pyslvs-UI\pyslvs_ui\__init__.py", line 49, in main
        from .core.main_window import MainWindow
      File "Y:\tmp\Pyslvs-UI\pyslvs_ui\core\main_window\__init__.py", line 24, in <module>
        from .io import IOMethodInterface
      File "Y:\tmp\Pyslvs-UI\pyslvs_ui\core\main_window\io.py", line 57, in <module>
        from .actions import ActionMethodInterface
      File "Y:\tmp\Pyslvs-UI\pyslvs_ui\core\main_window\actions.py", line 21, in <module>
        from .storage import StorageMethodInterface
      File "Y:\tmp\Pyslvs-UI\pyslvs_ui\core\main_window\storage.py", line 27, in <module>
        from .solver import SolverMethodInterface
      File "Y:\tmp\Pyslvs-UI\pyslvs_ui\core\main_window\solver.py", line 24, in <module>
        from pyslvs import (
    ImportError: cannot import name 'SolverSystem' from 'pyslvs'

**Comment by KmolYuan** [comment]
Kernel `pyslvs` might be not installed, please use `make build-kernel` to build the kernels.

Or install Pyslvs-UI with `pip install pyslvs-ui`.
